config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => 'registrations' ,:sessions => 'sessions'}
  resources :event_categories
  resources :events
  post 'attend_event' => 'events#attend_event', as: 'attend_event'
  #devise_scope :user do
   root to: "users/sessions#new"
   # post '/sign-up' => 'users/registrations#create'
    #post '/sign-in' => 'users/sessions#create'
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      can :read, Event, public: true
      if user.present?  # additional permissions for logged in users (they can read their own posts)

      if user.has_role? :admin # additional permissions for administrators
        can :manage, Event
      elsif user.has_role? :normal
        can :index, Event
        can :attend_event, Event
      end
    end
    # De    can :read, Post, public: true    can :read, Post, public: truefine abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :location, :event_date, :fees
  has_many :user_events
  has_many :users , through: :user_events
  belongs_to :event_category
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  has_many :events
end

app/models/role.rb
class Role < ApplicationRecord
	validates_presence_of :name
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_events
  has_many :events , through: :user_events
  has_and_belongs_to_many :roles
  
  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!

  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
   events_path
  end
  def after_sign_out_path_for(resource)
   events_path
  end

  # rescue_from CanCan::AccessDenied do |_exception|
  #   redirect_to root_url, notice: "Access Denied"
  # end
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  def index
    # @films = Film.all
    @event_categories = EventCategory.all.order('created_at DESC')
    # same as first line but sort in descending (DESC) order 
    # based on what time they were created
  end

  def new
  	@event_category = EventCategory.new
  end


  def create
    @event_category = EventCategory.new(event_category_params)
    if @event_category.save
      redirect_to @event_category
    else
      render 'new'
    end
  end

  def show
    @event_category = EventCategory.find(params[:id])
  end

  def edit
    @event_category = EventCategory.find(params[:id])
  end

  def update
    @event_category = EventCategory.find(params[:id])
    if @event_category.update(event_category_params)
      redirect_to @event_category
    else
      render 'edit'
    end
  end

  def destroy
    @event_category = EventCategory.find(params[:id])
    @event_category.destroy
    redirect_to root_path
  end

  private

  def event_category_params
  	# require the :film table
  	# security mesure called 'strong params' where we must permit
  	# the different attributes (:title, :description) that you 
  	# want to allow to be written to our database
  	params.require(:event_category).permit(:name, :description);
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    load_and_authorize_resource  class: "Event"
     #skip_authorize_resource only: :index
  def index
    @events = Event.all.order('created_at DESC')
  end

  def new
  	@event = Event.new
  end


  def create
    @event= Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event= Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    current_user.events.delete(@event)
    redirect_to root_path
  end

  def attend_event
    attend = params[:attend]
    user_event= UserEvent.where(user_id: current_user.id, event_id: params[:event_id]).first
    if user_event.present?
      user_event.update_attributes(attend: params[:attend])
    else
      current_user.user_events.create(event_id:params[:event_id], attend: attend)
    end
  end

  private

  def event_params
  	params.require(:event).permit(:name, :location, :event_date, :fees, :event_category_id);
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    super
  end
  def create
    # super
    @user = User.new(permitted_user)
    @user.roles << Role.where(name: "normal").first
    if @user.save(validate: false)
      respond_to do |format|
        format.html{ sign_in_and_redirect @user}
      end
    else
      @errors=@user.errors
      respond_to do |format|
        format.html {render "/devise/registrations/new"}
      end
    end
  end
  protected
  def permitted_user
    params.require(:user).permit(:email,:activation_token,:name,:gender,:password,:password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
   respond_to :json,:js,:html

  def create
    # byebug
    #  # resource = warden.authenticate!(:scope => resource_name, :recall => "sessions#handle_failed_login")
    #     respond_to do |format|
    #        resource = warden.authenticate!(:scope => resource_name, :recall => "sessions#handle_failed_login")
    #           format.html
    #           format.js 
    #      end
    super
    
    end
  def destroy
    super
  end
  def handle_failed_login
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
 
end

app/views/event_categories/_form.html.erb
<%= form_for @event_category do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/event_categories/edit.html.erb
<h3>Edit Event Category</h3>

<% # pulls in a partial from _form.html.erb %>
<%= render 'form' %>

app/views/event_categories/index.html.erb
<h3>Event Category Page</h3>


<% @event_categories.each do |ec| %>
  <h3><%= ec.name %></h3>
  <div>
    <%= ec.description   %>
  </div>
  <br>
<% end %>

app/views/event_categories/new.html.erb
<h3>Add New Event Category</h3>

<%# pulls in a partial from _form.html.erb %>
<%= render 'form' %>

app/views/event_categories/show.html.erb
<h3>Show Event Category</h3>

<h3><%= @event_category.name %></h3>

<p><%= @event_category.description %></p>

<%= link_to "Edit Event Category", edit_event_category_path(@event_category) %>
<br/>
<%= link_to "Delete Event Category", event_category_path(@event_category), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :location %><br>
  <%= f.text_field :location %><br>
  <br>
    <%= f.label :event_date %>
    <%= f.date_field :event_date, class: "datepicker" %>
  <br>
   <%= f.label :fees %><br>
  <%= f.text_field :fees %><br>
  <%= f.label :event_category%>
  <%= f.collection_select :event_category_id, EventCategory.all, :id, :name, include_blank: true %></br>
  <%= f.submit %>
<% end %>
  <script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker({
          format: "yyyy/mm/dd",
          autoclose: true,
          todayBtn: "linked",
          todayHighlight': true
                  });
      });
    </script>s

app/views/events/attend_event.js.erb
$(".message").html("Event Updated")

app/views/events/index.html.erb
</br>
</br>
<h1> All Events </h1>
<span class="message"></span>
<div class="row">
  <% @events.each do |event|%>
	  <div class="col-sm-4">
	    <div class="card">
	      <div class="card-body">
	        <h5 class="card-title"><%=event.name%></h5>
	        <p class="card-text"><%= event.event_category.name%></p>
	        <p class="card-text"><%= event.event_date%></p>

	        <%if current_user.gender  == "female"%>
	          <% if event.fees.present?%>
	            <%discounted_price= event.fees - (event.fees*5)/100%>
	          <%end%>
	          <p class="card-text"><%= discounted_price%></p>
	        <%else%>
	        <p class="card-text"><%= event.fees%></p>
	        <%end%>
	        <% if event.users.pluck(:id).include?(current_user.id) %>
 	        <%= link_to "Attending", attend_event_path(attend: false, event_id: event.id), method: :post, class: "btn btn-primary", remote: true %>
	        <%else%>
     	        <%= link_to "Attend", attend_event_path(attend: true, event_id: event.id), method: :post, class: "btn btn-primary", remote: true %>
	        <%end%>
	      </div>
	    </div>
	  </div>
  <%end%>
</div>

app/views/events/new.html.erb
<h3>Add New Event Category</h3>

<% # pulls in a partial from _form.html.erb %>
<%= render 'form' %>

app/views/events/show.html.erb
<h3>Show Event </h3>

<h3><%= @event.name %></h3>

<p><%= @event.location %></p>
<p> <%= @event.event_date%> </p>
<p> <%= @event.event_category.name%>

<%= link_to "Edit Event", edit_event_category_path(@event) %>
<br/>
<%= link_to "Delete Event", event_category_path(@event), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bukukas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render partial: "shared/header" %>
        <%= yield %>
      <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="jumbotron">
  <div style="float:left;">
    <h2> Event Booking Platform </h2>
  </div>
  <div style="float:right">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
         Logged in as <strong><%= current_user.email %></strong>.
         <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
         <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
         <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
         <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
   </div>
 </div>